version: '3.3'

services:
  bot:
    build:
      context: .
      dockerfile:
        Dockerfile
    restart:
       on-failure
    volumes:
        - ".:/usr/src/app"

  postgres:
    container_name: postgresql
    image:
       postgres:10
    volumes:
      - "./postgres/data:/var/lib/postgresql/data/pgdata"
    env_file:
      - ./pg.evn
    restart:
        always
    ports:
        - 5432:5432

  redis:
    container_name: redis
    image:
      redis:alpine
    ports:
      - "6379:6379"
    command:
        - 'redis-server'
        - '--loglevel ${REDIS_LOGLEVEL:-warning}'
        - '--databases 2'
        - '--maxmemory ${REDIS_MAXMEM:-50mb}'
        - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
    volumes:
      - ../data/redis:/data
    restart: always

  adminer:
    image:
       adminer
    restart:
      always
    ports:
      - 8080:8080