version: '3'

services:
  bot:
    build:
      context: .
      dockerfile:
        Dockerfile

    restart:
       on-failure
    volumes:
        - ".:/usr/src/app"
    command:
          "sh -ac 'cd /usr/src/app && python3 start_poling.py'; ls"
  postgres:
    container_name: postgres
    image:
       postgres:10
    volumes:
      - "./postgres/data:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_USER: "eventstracker"
      POSTGRES_PASSWORD: "A3dSA24Dctf2v4HE"
      PGDATA: "./postgres/data:/var/lib/postgresql/data/pgdata"
    restart:
        always
    ports:
        - 5432:5432
  redis:
    image:
     redis:5
    restart:
      always
    ports:
      - 6379:6379
    command:
       redis-server --appendonly yes

  adminer:
    image:
       adminer
    restart:
      always
    ports:
      - 8080:8080