version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile:
        Dockerfile
    depends_on:
      - postgres
      - redis
      - influxdb
    env_file:
      evn/bot.evn
    restart:
       on-failure
    volumes:
        - ".:/usr/src/app"

  postgres:
    container_name:  postgres
    image:
       postgres:13
    volumes:
      - "./postgres/data:/var/lib/postgresql/data/pgdata"
    env_file:
      - evn/pg.env
    restart:
        always
    ports:
        - 5432:5432

  redis:
    container_name: redis
    image:
      redis:alpine
    ports:
      - "6379:6379"
    command:
        - 'redis-server'
        - '--loglevel ${REDIS_LOGLEVEL:-warning}'
        - '--databases 2'
        - '--maxmemory ${REDIS_MAXMEM:-50mb}'
        - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
    volumes:
      - ../data/redis:/data
    restart: always

  influxdb:
    image: influxdb:1.8
    container_name: "influxdb"
    restart: always
    volumes:
      - "./influxdb:/var/lib/influxdb"
    env_file:
      - evn/influxdb.evn
    ports:
      -  8086:8086

  grafana:
      image: grafana/grafana:7.3.4
      container_name: "grafana"
      restart: always
      volumes:
        - "./grafana/data:/var/lib/grafana"
      environment:
        - GF_DATE_FORMATS_DEFAULT_TIMEZONE=browser
      ports:
        - 3000:3000
      user: "472"

  adminer:
    image:
       adminer
    restart:
      always
    ports:
      - 8080:8080
